<?php
/**
 * @package CaluconEmbedGate
 */

namespace CaluconEmbedGate\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Every English string the WordPress-free layers pass through the $t()
 * bridge must have a literal __() mirror in languages/strings.php — that
 * file is what translate.wordpress.org extracts. It is generated by
 * tests/bin/generate-pot.php; this test fails the moment a $t() string is
 * added without regenerating it.
 */
final class StringsMapTest extends TestCase {

	public function test_every_t_string_in_src_is_mirrored(): void {
		$root = dirname( __DIR__, 2 );
		// strings.php calls __() at load time; scan it as text instead of
		// including it into the WordPress-free suite.
		$mirror = (string) file_get_contents( $root . '/languages/strings.php' );
		preg_match_all( "/__\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $mirror, $mm );
		$map = array_fill_keys( array_map( static function ( string $literal ): string {
			return str_replace( "\\'", "'", $literal );
		}, $mm[1] ), true );
		self::assertNotEmpty( $map );

		$found = array();
		$it    = new \RecursiveIteratorIterator( new \RecursiveDirectoryIterator( $root . '/src' ) );
		foreach ( $it as $file ) {
			if ( 'php' !== $file->getExtension() ) {
				continue;
			}
			$code = (string) file_get_contents( (string) $file );
			if ( preg_match_all( "/\\\$t\\(\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*\\)/", $code, $m ) ) {
				foreach ( $m[1] as $literal ) {
					$found[ str_replace( "\\'", "'", $literal ) ] = (string) $file;
				}
			}
		}

		self::assertGreaterThan( 30, count( $found ), 'the $t() scan found too few strings — regex drift?' );
		foreach ( $found as $text => $file ) {
			self::assertArrayHasKey( $text, $map, "$file uses \$t() with a string missing from languages/strings.php — run php tests/bin/generate-pot.php" );
		}
	}
}
